### ISSUE TITLE
Another resign condition?

### ISSUE THREAD

**Issue by gooooloo** [mokemokechicken/reversi-alpha-zero#11]
@mokemokechicken 

https://github.com/mokemokechicken/reversi-alpha-zero/blob/e79d92ffb58cf06e8d93036e7d33f2441ca3d569/src/reversi_zero/agent/player.py#L79-L80

Do you think it is reasonable to resign if **min**(varq, (varn==0)*10)> 0.8 (or 0.9)?

As you said the <-0.8 resignation helps a lot due to its ignorance on one-side game state. I also verified the effect on my local run. Then >0.8 is also a one-side game. And I guess MCTS is strong enough to guide ai to win on this situation? Then the NN will be more accurate due to less sample space. I know it is not mentioned on Deepmind Paper. Maybe it is because of large state space of Go game. But maybe it's worth trying on Reversi?What do you think?

**Comment by mokemokechicken** [comment]
@gooooloo 

I can not clearly point out the problem on play data generation, but I feel a bit strange.

1. even if black is almost winning, it is strange to decide "resign by white" by black. 
2. If we want to implement "think very deep(ex. search num to 1600) before resigning", that logic becomes an obstacle.

**Comment by gooooloo** [comment]
No I am not saying "resign by white" by black, but something like both players agree to stop the game  under that condition. Maybe "resign" is not a correct word here, but it does the similar thing with alphago zero: stop the game earlier and keep training data simpler. And we can still keep same "false positive adjustment" mechanism.

About the MCTS: Resigning is self-play thing. When in evaluate/play_with_human, AI don't have resign mechanism, AI have to play till the end. But as AI resigned to avoid NN training on that situation, so MCTS is the only thing that can lead to final win.

Never mind, I can test locally and update the result later.

**Comment by gooooloo** [comment]
Close it for now. Once I have result later I will update.

**Comment by gooooloo** [comment]
Update: I realize that it is already implicitly done in current resign design: when selfplay, since both players are using same model, when one side's model predicts the state value is lower than threshold, than the other side will predict the state value larger than -threshold, and vice versa.
