### ISSUE TITLE
invalid correct moves

### ISSUE THREAD

**Issue by apollo-time** [mokemokechicken/reversi-alpha-zero#29]
https://github.com/mokemokechicken/reversi-alpha-zero/blob/4cca25a16168b7a76c9d08eb0670da25f565d04c/src/reversi_zero/lib/bitboard.py#L53

I found 11 valid moves using find_correct_moves on the Board(black=147618596785664,white=4812688517050430, current_play=black).
But there are 10 correct moves actually.
Please check find_correct_moves function.
![image](https://user-images.githubusercontent.com/9794932/34637985-7db9ddac-f2fd-11e7-9e57-4498c6f05393.png)

**Comment by fuzzthink** [comment]
So function is ok?

**Comment by apollo-time** [comment]
Yes, I was wrong.
