### ISSUE TITLE
automatically ntest 

### ISSUE THREAD

**Issue by gooooloo** [mokemokechicken/reversi-alpha-zero#39]
@mokemokechicken  in ReadMe you said:

> NBoard cannot play with two different engines (maybe).

I feel it can in another way. From this [source code of NBoard](https://github.com/weltyc/nboard/blob/3f3c4d483d0e8617c84e1d0a8de1acd4676a2cdb/src/com/welty/nboard/nboard/Install.java#L78), seems like it just run a `ntest` executable, then communicate to it via NBoard protocol. Since you have understand that protocol well, you can also launch `ntest` and communicate with it in your code. Then you can play your model with ntest without manual intervention. If you want to check game detail, just save the movement and replay it.

**Comment by mokemokechicken** [comment]
@gooooloo 

Thank you for your information!

Thanks to you, after knowing about Nboard and the protocol,
I developed [reversi-arena](https://github.com/mokemokechicken/reversi-arena) which evaluate two engines that implement NBoard Protocol.

Now, I am using the arena to evaluate my model with ntest:X.
Please try using it if you like!

**Comment by gooooloo** [comment]
@mokemokechicken COOL!
