### ISSUE TITLE
Child seeds being identical to the parent seed may nullify the effect of multi-processing/threading

### ISSUE THREAD

**Issue by AranKomat** [mokemokechicken/reversi-alpha-zero#47]
This is my finding from a toy version of my customization of Akababa's implementation, but I'm certain this is relevant to your implementation and at least worth asking here, as your seeding part isn't essentially different from his. I've noticed that, since each process/thread shares the same seed, each process/thread generates the same result (e.g. state transition during simulation) regardless of the underlying probability distribution. Some processes/threads are faster than others, so eventually you may not find this deterministic behavior, as some processes/threads yield different outputs at the same instant despite the identical pseudo-random sequence generation. Did you find this problematic? I don't think this has been mentioned yet. 

Relevant sources:
[best-seed-for-parallel-process](https://stackoverflow.com/questions/2396209/best-seed-for-parallel-process)
[Random seed is replication across child processes #9650
](https://github.com/numpy/numpy/issues/9650) [seeding-random-number-generators-in-parallel-programs](https://stackoverflow.com/questions/29854398/seeding-random-number-generators-in-parallel-programs)

**Comment by gooooloo** [comment]
This is an interesting topic!

> since each process/thread shares the same seed

Is that true? I see @mokemokechicken does reseeding [here](https://github.com/mokemokechicken/reversi-alpha-zero/blob/db3c039d91781282299c76e190d34ac10a8c73b4/src/reversi_zero/worker/self_play.py#L96) in subprocess. The parameter is None, then Python will try to read data from /dev/urandom, according to this [document](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState).

**Comment by mokemokechicken** [comment]
@AranKomat 
As @gooooloo said, I think I solved the problem.
Actually before reseeding, there were many same games.

**Comment by AranKomat** [comment]
I guess I misinterpreted that line... I'm sorry, but thanks so much!
