### ISSUE TITLE
a question about reloading model

### ISSUE THREAD

**Issue by gooooloo** [mokemokechicken/reversi-alpha-zero#48]
https://github.com/mokemokechicken/reversi-alpha-zero/blob/db3c039d91781282299c76e190d34ac10a8c73b4/src/reversi_zero/agent/api.py#L81

When reloading, some self play game may be still in progress. Will this reloading be OK? Some games will be using old model in first half of game, and new model in second half of game. Some more discussion can be seen [here](https://github.com/Akababa/Chess-Zero/issues/8). In another [fork](https://github.com/benediamond/chess-alpha-zero/commit/f9d30b3d01d7435264c98814bdc36a5a427ca072#diff-d9304e2104e0753fc21ff9dec7a44e64R47) there is a fix of this, but it will cause some idle time of cpu.

Or, you are aware of this issue, and think it is ok? As we can see, you model are making good progress as well...

**Comment by mokemokechicken** [comment]
@gooooloo 

I think that it is ok to reload the model even during the game.
It seems that it makes little sense to keep model identical, because it is ok to have randomness in self-play games and there is possibility that the newer model has better policy and value.

**Comment by gooooloo** [comment]
OK. Got you. Thanks.
